version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web_app
    image: django:app
    ports:
      - 8000:8000
    links:
      - "redis:redis"

  celery:
    restart: always
    build:
      context: .
    command: celery -A factory worker -l DEBUG
    volumes:
      - .:/code
    container_name: celery
    depends_on:
      - redis
      - app
    links:
      - "redis:redis"