# Generated by Django 4.2.5 on 2023-10-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram', '0002_telegramuserconnecttry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuserconnecttry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
